server:
  port: 9090
  address: 0.0.0.0

remote:
  port: 9090
  address: 172.16.61.151

spring:
  application:
    name: textBook

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.84.152:3307/textbook?
    username: root
    password: root

    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      jedis:
        pool:
          min-idle: 4
          max-wait: 5000

file:
  staticAccessPath: /api/file/**
#  uploadFolder: /home/upload/
  uploadFolder: d://upload/

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        min-idle: 4
        max-wait: 5000

logging:
  level:
    com.it666.textbook: debug

#开启驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true