server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: textBook

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/textbook?serverTimezone=UTC
    username: root
    password: chenjinjie

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        min-idle: 4
        max-wait: 5000

logging:
  level:
    com.it666.textbook: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true